aws_config:
  aws_key: AKIAJWONY62CEX6DIRAA
  aws_secret: 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
  aws_region: us-east-2
  aws_bucket: com.rivery.dev.athena.workspace
#  aws_bucket: rivery-dev-tests